-- CloudOps Platform baseline schema.
-- Identifiers are UUIDv7 values generated by the application. Enumerations are stored as text
-- with CHECK constraints so values stay readable in ad-hoc queries and adding a value is a
-- simple constraint change.

CREATE TABLE user_accounts (
    id            uuid         PRIMARY KEY,
    email         varchar(254) NOT NULL,
    display_name  varchar(100) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role          varchar(20)  NOT NULL,
    version       bigint       NOT NULL DEFAULT 0,
    created_at    timestamptz  NOT NULL,
    updated_at    timestamptz  NOT NULL,
    CONSTRAINT uq_user_accounts_email UNIQUE (email),
    CONSTRAINT ck_user_accounts_email_normalized CHECK (email = lower(email)),
    CONSTRAINT ck_user_accounts_role CHECK (role IN ('VIEWER', 'OPERATOR', 'ADMIN'))
);

CREATE TABLE teams (
    id            uuid          PRIMARY KEY,
    slug          varchar(63)   NOT NULL,
    name          varchar(100)  NOT NULL,
    description   varchar(1000),
    contact_email varchar(254),
    version       bigint        NOT NULL DEFAULT 0,
    created_at    timestamptz   NOT NULL,
    updated_at    timestamptz   NOT NULL,
    CONSTRAINT uq_teams_slug UNIQUE (slug)
);

CREATE TABLE workloads (
    id             uuid          PRIMARY KEY,
    slug           varchar(63)   NOT NULL,
    name           varchar(100)  NOT NULL,
    description    varchar(2000),
    team_id        uuid          NOT NULL,
    criticality    varchar(10)   NOT NULL,
    repository_url varchar(500),
    runbook_url    varchar(500),
    version        bigint        NOT NULL DEFAULT 0,
    created_at     timestamptz   NOT NULL,
    updated_at     timestamptz   NOT NULL,
    CONSTRAINT uq_workloads_slug UNIQUE (slug),
    CONSTRAINT fk_workloads_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT,
    CONSTRAINT ck_workloads_criticality CHECK (criticality IN ('HIGH', 'MEDIUM', 'LOW'))
);

CREATE INDEX ix_workloads_team ON workloads (team_id);

-- Deployment records are history: they disappear only together with their workload.
CREATE TABLE deployments (
    id               uuid          PRIMARY KEY,
    workload_id      uuid          NOT NULL,
    environment      varchar(20)   NOT NULL,
    release_version  varchar(100)  NOT NULL,
    commit_sha       varchar(40),
    outcome          varchar(20)   NOT NULL,
    notes            varchar(2000),
    deployed_by_id   uuid          NOT NULL,
    deployed_by_name varchar(100)  NOT NULL,
    deployed_at      timestamptz   NOT NULL,
    CONSTRAINT fk_deployments_workload FOREIGN KEY (workload_id) REFERENCES workloads (id) ON DELETE CASCADE,
    CONSTRAINT fk_deployments_deployed_by FOREIGN KEY (deployed_by_id) REFERENCES user_accounts (id),
    CONSTRAINT ck_deployments_environment CHECK (environment IN ('DEVELOPMENT', 'STAGING', 'PRODUCTION')),
    CONSTRAINT ck_deployments_outcome CHECK (outcome IN ('SUCCEEDED', 'FAILED', 'ROLLED_BACK')),
    CONSTRAINT ck_deployments_commit_sha CHECK (commit_sha ~ '^[0-9a-f]{7,40}$')
);

-- Serves both per-workload history and the "latest deployment per environment" lookup.
CREATE INDEX ix_deployments_workload_env_time ON deployments (workload_id, environment, deployed_at DESC);
CREATE INDEX ix_deployments_env_time ON deployments (environment, deployed_at DESC);

-- Incidents are retained for audit; a workload with incidents cannot be deleted.
CREATE TABLE incidents (
    id             uuid          PRIMARY KEY,
    workload_id    uuid          NOT NULL,
    title          varchar(200)  NOT NULL,
    summary        varchar(4000),
    severity       varchar(10)   NOT NULL,
    status         varchar(20)   NOT NULL,
    opened_by_id   uuid          NOT NULL,
    opened_by_name varchar(100)  NOT NULL,
    opened_at      timestamptz   NOT NULL,
    mitigated_at   timestamptz,
    resolved_at    timestamptz,
    version        bigint        NOT NULL DEFAULT 0,
    created_at     timestamptz   NOT NULL,
    updated_at     timestamptz   NOT NULL,
    CONSTRAINT fk_incidents_workload FOREIGN KEY (workload_id) REFERENCES workloads (id) ON DELETE RESTRICT,
    CONSTRAINT fk_incidents_opened_by FOREIGN KEY (opened_by_id) REFERENCES user_accounts (id),
    CONSTRAINT ck_incidents_severity CHECK (severity IN ('SEV1', 'SEV2', 'SEV3', 'SEV4')),
    CONSTRAINT ck_incidents_status CHECK (status IN ('OPEN', 'MITIGATED', 'RESOLVED')),
    CONSTRAINT ck_incidents_resolution CHECK ((status = 'RESOLVED') = (resolved_at IS NOT NULL)),
    CONSTRAINT ck_incidents_chronology CHECK (
        (mitigated_at IS NULL OR mitigated_at >= opened_at) AND
        (resolved_at IS NULL OR resolved_at >= opened_at))
);

CREATE INDEX ix_incidents_workload_opened ON incidents (workload_id, opened_at DESC);
CREATE INDEX ix_incidents_status_opened ON incidents (status, opened_at DESC);
-- The dashboard only scans unresolved incidents; a partial index keeps that lookup small.
CREATE INDEX ix_incidents_active ON incidents (workload_id) WHERE status <> 'RESOLVED';

CREATE TABLE incident_updates (
    id             uuid          PRIMARY KEY,
    incident_id    uuid          NOT NULL,
    message        varchar(4000) NOT NULL,
    status_after   varchar(20)   NOT NULL,
    severity_after varchar(10)   NOT NULL,
    author_id      uuid          NOT NULL,
    author_name    varchar(100)  NOT NULL,
    posted_at      timestamptz   NOT NULL,
    CONSTRAINT fk_incident_updates_incident FOREIGN KEY (incident_id) REFERENCES incidents (id) ON DELETE CASCADE,
    CONSTRAINT fk_incident_updates_author FOREIGN KEY (author_id) REFERENCES user_accounts (id),
    CONSTRAINT ck_incident_updates_status CHECK (status_after IN ('OPEN', 'MITIGATED', 'RESOLVED')),
    CONSTRAINT ck_incident_updates_severity CHECK (severity_after IN ('SEV1', 'SEV2', 'SEV3', 'SEV4'))
);

CREATE INDEX ix_incident_updates_incident_time ON incident_updates (incident_id, posted_at);
